src/AppBundle/Entity/Product.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Description of Customer
 * @ORM\Entity
 * @ORM\Table(name="Product")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ProductRepository")
 */
class Product {
    
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
    
    /**
     * @ORM\Column(type="text")
     * @Assert\Valid
     * @Assert\NotNull
     */
    protected $name;
    
    /**
     * @ORM\Column(type="decimal", precision=6, scale=2)
     */
    protected $price;
    
    /**
     * @ORM\Column(type="boolean")
     */
    protected $active;
    
    /**
     * @ORM\OneToMany(targetEntity="SingleOrder", mappedBy="product")
     */
    protected $orders;

    /**
     * Constructor
     */	
    public function __construct($name = null, $price = 0)
    {
        $this->orders = new \Doctrine\Common\Collections\ArrayCollection();
		$this->price = $price;
		$this->name = $name;
		$this->active = true;
    }
    
    public function getDisplayName(){
        return $this->getName().' - '.$this->getPrice().'€';
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Product
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set price
     *
     * @param string $price
     *
     * @return Product
     */
    public function setPrice($price)
    {
        $this->price = $price;

        return $this;
    }

    /**
     * Get price
     *
     * @return string
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Add order
     *
     * @param \AppBundle\Entity\SingleOrder $order
     *
     * @return Product
     */
    public function addOrder(\AppBundle\Entity\SingleOrder $order)
    {
        $this->orders[] = $order;

        return $this;
    }

    /**
     * Remove order
     *
     * @param \AppBundle\Entity\SingleOrder $order
     */
    public function removeOrder(\AppBundle\Entity\SingleOrder $order)
    {
        $this->orders->removeElement($order);
    }

    /**
     * Get orders
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getOrders()
    {
        return $this->orders;
    }

    /**
     * Set active
     *
     * @param boolean $active
     *
     * @return Product
     */
    public function setActive($active)
    {
        $this->active = $active;

        return $this;
    }

    /**
     * Get active
     *
     * @return boolean
     */
    public function getActive()
    {
        return $this->active;
    }
}

src/AppBundle/Entity/TotalOrder.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Description of Customer
 * @ORM\Entity
 * @ORM\Table(name="TotalOrder")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\TotalOrderRepository")
 */
class TotalOrder {

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="text", nullable = true)
     */
    protected $text;
    
    /**
     * @ORM\Column(type="text", nullable = false)
     */
    protected $code;

    /**
     *
     * @ORM\Column(name="the_date", type="date")
     * @var \DateTime
     */
    protected $date;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $active;

    /**
     * @ORM\OneToMany(targetEntity="SingleOrder", mappedBy="order")
     */
    protected $orders;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set text
     *
     * @param string $text
     *
     * @return Slot
     */
    public function setText($text) {
        $this->text = $text;

        return $this;
    }

    /**
     * Get text
     *
     * @return string
     */
    public function getText() {
        return $this->text;
    }

    /**
     * Constructor
     */
    public function __construct() {
        $this->orders = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add order
     *
     * @param \AppBundle\Entity\SingleOrder $order
     *
     * @return TotalOrder
     */
    public function addOrder(\AppBundle\Entity\SingleOrder $order) {
        $this->orders[] = $order;

        return $this;
    }

    /**
     * Remove order
     *
     * @param \AppBundle\Entity\SingleOrder $order
     */
    public function removeOrder(\AppBundle\Entity\SingleOrder $order) {
        $this->orders->removeElement($order);
    }

    /**
     * Get orders
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getOrders() {
        return $this->orders;
    }

    /**
     * Set active
     *
     * @param boolean $active
     *
     * @return TotalOrder
     */
    public function setActive($active) {
        $this->active = $active;

        return $this;
    }

    /**
     * Get active
     *
     * @return boolean
     */
    public function getActive() {
        return $this->active;
    }


    /**
     * Set date
     *
     * @param \DateTime $date
     *
     * @return TotalOrder
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }
    
    public function getAmount(){
        $total = 0;
        foreach ($this->orders as $order){
            $total += $order->getProduct()->getPrice();
        }
        return $total;
    }

    /**
     * Get date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set code
     *
     * @param string $code
     *
     * @return TotalOrder
     */
    public function setCode($code)
    {
        $this->code = $code;

        return $this;
    }

    /**
     * Get code
     *
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }
}

src/AppBundle/Controller/OrdersController.php
<?php

namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use AppBundle\Entity\TotalOrder;
use AppBundle\Entity\SingleOrder;
use AppBundle\Form\SingleOrderType;
use AppBundle\Form\ConfirmPayedType;
use AppBundle\Form\TotalOrderType;
use Symfony\Component\Form\FormError;

/**
 * @Route("/orders")
 */
class OrdersController extends Controller {

    /**
     * @Route("/", name="orders")
     * @Template
     */
    public function historyAction(Request $request) {
        $allOrders = $this->getDoctrine()
                ->getRepository('AppBundle:TotalOrder')
                ->findOrders();

        return array('allOrders' => $allOrders);
    }

    /**
     * @Route("/{totalId}", 
     * requirements = { "totalId" = "[0-9]+" },
     * name="displayTotalOrder")
     * @Template
     */
    public function displayTotalOrderAction(Request $request, $totalId) {

        $totalOrder = $this->getDoctrine()
                ->getRepository('AppBundle:TotalOrder')
                ->find($totalId);

        return array('totalOrder' => $totalOrder);
    }

    /**
     * @Route("/{totalId}/byProduct", 
     * requirements = { "totalId" = "[0-9]+" },
     * name="totalByProduct")
     * @Template
     */
    public function totalByProductAction(Request $request, $totalId) {

        $totalOrder = $this->getDoctrine()
                ->getRepository('AppBundle:TotalOrder')
                ->find($totalId);

        $orders = $totalOrder->getOrders();
        $products = array();
        foreach ($orders as $order) {
            $product = $order->getProduct();
            $key = $product->getId();
            if (strlen($order->getText()) > 0) {
                $key .= strtolower($order->getText());
            }

            if (isset($products[$key])) {
                $productArr = $products[$key];
                $comments = $productArr['comments'];
                $productArr['count'] = $productArr['count'] + 1;
            } else {
                $productArr = array();
                $productArr["product"] = $product;
                $productArr['count'] = 1;
                $comments = array();
                if (strlen($order->getText()) > 0) {
                    array_push($comments, $order->getText());
                }
            }
            $productArr["comments"] = $comments;
            $products[$key] = $productArr;
        }


        return array('totalOrder' => $totalOrder, 'products' => $products);
    }

    /**
     * @Route("/{totalId}/createSingle", 
     * requirements = { "totalId" = "[0-9]+" },
     * name="createSingle")
     * @Template("AppBundle:Orders:single.html.twig")
     */
    public function createSingleAction(Request $request, $totalId) {

        $totalOrder = $this->getDoctrine()
                ->getRepository('AppBundle:TotalOrder')
                ->find($totalId);

        $singleOrder = new \AppBundle\Entity\SingleOrder();
        $singleOrder->setOrder($totalOrder);
        $singleOrder->setPayed(false);

        $form = $this->createForm(SingleOrderType::class, $singleOrder);
        $form->handleRequest($request);

        if (!$totalOrder->getActive()) {
            $form->addError(new FormError('The Order has already been closed. Changes are no longer possible'));
        }

        if ($form->get('cancel')->isClicked()) {
            return $this->redirectToRoute('index');
        }

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($singleOrder);
            $em->flush();
            return $this->redirectToRoute('confirmPayed', array('singleId' => $singleOrder->getId()));
        }

        return array(
            'form' => $form->createView());
    }

    /**
     * @Route("/single/{singleId}/confirmPayed", 
     * requirements = { "totalId" = "[0-9]+" },
     * name="confirmPayed")
     * @Template("AppBundle:Orders:confirmPayed.html.twig")
     */
    public function confirmPayedAction(Request $request, $singleId) {
        $singleOrder = $this->getDoctrine()
                ->getRepository('AppBundle:SingleOrder')
                ->find($singleId);

        $formData = array('code' => '', 'singleOrder' => $singleOrder);

        $form = $this->createForm(ConfirmPayedType::class, $formData);
        $form->handleRequest($request);

        if (!$singleOrder->getOrder()->getActive()) {
            $form->addError(new FormError('The Order has already been closed. Changes are no longer possible'));
        }

        if ($form->get('cancel')->isClicked()) {
            return $this->redirectToRoute('index');
        }

        if ($form->isValid()) {
            $expectedCode = $singleOrder->getOrder()->getCode();
            $enteredCode = $form->get('code')->getData();
            $logger = $this->get('logger');
            $logger->info('Expected: ' . $expectedCode);
            $logger->info('Entered: ' . $enteredCode);
            if (strcasecmp($expectedCode, $enteredCode) != 0) {
                $form->get('code')->addError(new FormError('The code you entered is not correct.'));
                return array(
                    'form' => $form->createView(), 'singleOrder' => $singleOrder);
            }
            $singleOrder->setPayed(true);
            $em = $this->getDoctrine()->getManager();
            $em->persist($singleOrder);
            $em->flush();
            return $this->redirectToRoute('index');
        }

        return array(
            'form' => $form->createView(), 'singleOrder' => $singleOrder);
    }

    /**
     * @Route("/single/{singleId}", 
     * requirements = { "singleId" = "[0-9]+" },
     * name="editSingle")
     * @Template("AppBundle:Orders:single.html.twig")
     */
    public function editSingleAction(Request $request, $singleId) {

        $singleOrder = $this->getDoctrine()
                ->getRepository('AppBundle:SingleOrder')
                ->find($singleId);

        $form = $this->createForm(SingleOrderType::class, $singleOrder);
        $form->handleRequest($request);

        if (!$singleOrder->getOrder()->getActive()) {
            $form->addError(new FormError('The Order has already been closed. Changes are no longer possible'));
        }

        if ($form->get('cancel')->isClicked()) {
            return $this->redirectToRoute('index');
        }

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($singleOrder);
            $em->flush();
            if($singleOrder->getPayed()){
                return $this->redirectToRoute('index');
            }
            return $this->redirectToRoute('confirmPayed', array('singleId' => $singleOrder->getId()));
        }

        return array(
            'form' => $form->createView());
    }

    /**
     * @Route("/single/{singleId}/delete", 
     * requirements = { "singleId" = "[0-9]+" },
     * name="deleteSingle")
     */
    public function deleteSingleAction(Request $request, $singleId) {


        $em = $this->getDoctrine()->getManager();
        $singleOrder = $em->getRepository('AppBundle:SingleOrder')->find($singleId);
        if (isset($singleOrder)) {

            if ($singleOrder->getOrder()->getActive()) {
                $em->remove($singleOrder);
                $em->flush();
            }
        }
        return new Response(
                'Content', Response::HTTP_OK, array('content-type' => 'text/html'));
    }

    private function createCode() {
        $alpha = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $numeric = '0123456789';
        return substr(str_shuffle($alpha), 0, 1) . substr(str_shuffle($numeric), 0, 1);
    }

    /**
     * @Route("/createTotal", name="createTotalOrder")
     * @Security("has_role('ROLE_ADMIN')")
     * @Template("AppBundle:Orders:total.html.twig")
     */
    public function createTotalAction(Request $request) {

        $totalOrder = new TotalOrder();
        $totalOrder->setActive(true);
        $totalOrder->setDate(new \DateTime());
        $totalOrder->setCode($this->createCode());
        $form = $this->createForm(TotalOrderType::class, $totalOrder);
        $form->handleRequest($request);

        if ($form->get('cancel')->isClicked()) {
            return $this->redirectToRoute('index');
        }

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($totalOrder);
            $em->flush();
            return $this->redirectToRoute('index');
        }

        return array(
            'form' => $form->createView());
    }

    /**
     * @Route("/{totalId}/edit", 
     *          name="editTotal",
     *          requirements = { "totalId" = "[0-9]+" })
     * @Security("has_role('ROLE_ADMIN')")
     * @Template("AppBundle:Orders:total.html.twig")
     */
    public function editTotalAction(Request $request, $totalId) {

        $totalOrder = $this->getDoctrine()
                ->getRepository('AppBundle:TotalOrder')
                ->find($totalId);

        $form = $this->createForm(TotalOrderType::class, $totalOrder);
        $form->handleRequest($request);

        if ($form->get('cancel')->isClicked()) {
            return $this->redirectToRoute('index');
        }

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($totalOrder);
            $em->flush();
            return $this->redirectToRoute('index');
        }

        return array(
            'form' => $form->createView());
    }

}

src/AppBundle/Resources/views/Orders/confirmPayed.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_3_layout.html.twig' %}
{% block content %}
    {{ form_start(form) }}
    {{ form_errors(form) }}
    <div class="jumbotron">
        <h1>{{singleOrder.name}}, please confirm your payment</h1>
        <p>Enter todays code in the box below to confirm your payment. You will find this code at the paybox.</p>
        <p>
            {{ form_label(form.code) }}
            {{ form_errors(form.code) }}
            {{ form_widget(form.code) }}
        </p>     
        {{ form_widget(form.save) }} {{ form_widget(form.cancel) }}
    </div>

    {{ form_end(form) }}
{% endblock %}

src/AppBundle/Resources/views/Orders/createSingle.html.twig
{% extends 'base.html.twig' %}
{% block content %}

    {{ form_start(form) }}
    {{ form_errors(form) }}
    <h3>Place your Order</h3>
    <div class="container-fluid">
        <div class="row">   
            <div class="col-md-3">
                {{ form_label(form.name) }}
                {{ form_errors(form.name) }}
                {{ form_widget(form.name) }}
            </div>
            <div class="col-md-3">
                {{ form_label(form.text) }}
                {{ form_errors(form.text) }}
                {{ form_widget(form.text) }}
            </div>

        </div><br/>
        <div class="row"><div class="col-md-12">
                {{ form_widget(form.save) }} {{ form_widget(form.cancel) }}
            </div>
        </div>
    </div>

    {{ form_end(form) }}
{% endblock %}

src/AppBundle/Resources/views/Orders/createTotal.html.twig
{% extends 'base.html.twig' %}
{% block content %}

    {{ form_start(form) }}
    {{ form_errors(form) }}
    <h3>Total Order</h3>
    <div class="container-fluid">
        <div class="row">

            <div class="col-md-3">
                {{ form_label(form.active) }}
                {{ form_errors(form.active) }}
                {{ form_widget(form.active) }}
            </div>
            
            <div class="col-md-3">
                {{ form_label(form.text) }}
                {{ form_errors(form.text) }}
                {{ form_widget(form.text) }}
            </div>
            
        </div><br/>
        <div class="row"><div class="col-md-12">
                {{ form_widget(form.save) }} {{ form_widget(form.cancel) }}
            </div>
        </div>
    </div>

    {{ form_end(form) }}
{% endblock %}

src/AppBundle/Resources/views/Orders/displayTotalOrder.html.twig
{% extends 'base.html.twig' %}
{% block head_script %}
    {{ parent() }}
    <script>
        function removeSingle($urlToRemove) {

            $.get($urlToRemove, function (data) {
                location.reload();
            });

        }
    </script>
{% endblock %}

{% block content %}
    <h3>Orders for {{totalOrder.date|date('d.m.y')}}</h3>
    <div class="container container-fluid">
        <div class="row">
            <div class="col-md-6">
                <h3>Total Amount:&nbsp;<b>{{totalOrder.amount}}€</b></h3>
            </div><div class="col-md-6">
                <h3>Total Orders Count:&nbsp;<b>{{totalOrder.orders|length}}</b></h3>
            </div>
        </div>
        <div class="row">
            {% if totalOrder.active %}
                <div class="col-md-4">
                    <h3><a href="{{path('createSingle',{'totalId':totalOrder.id})}}"><i class="fa fa-plus-square-o" aria-hidden="true"></i>&nbsp;Place new Order</a></h3>
                </div>
            {% else %}
                <div class="col-md-4">
                    <h3 style="color: orange"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i>&nbsp;This order is closed.</h3>
                </div>
            {% endif %}

            {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                <div class="col-md-4">
                    <a href="{{path('editTotal',{'totalId':totalOrder.id})}}">
                        <h3><i class="fa fa-pencil-square-o" aria-hidden="true"></i>&nbsp;Edit Order</h3>
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="{{path('totalByProduct',{'totalId':totalOrder.id})}}">
                        <h3><i class="fa fa-eye" aria-hidden="true"></i>&nbsp;Display By Product</h3>
                    </a>
                </div>
            {% endif %}
        </div>

        {% for order in totalOrder.orders %}
            <div class="row" style="background-color: {{ cycle(["#e6f2ff", "white"], loop.index) }}">
                {% if totalOrder.active %}
                    <div class="col-md-1">
                        <a href="{{path('editSingle',{'singleId':order.id})}}">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                        </a>
                        <a href="#" onClick="removeSingle('{{path('deleteSingle',{'singleId':order.id})}}');">
                            <i class="fa fa-trash-o" aria-hidden="true"></i></i>
                        </a>
                    </div>
                {% endif %}
                <div class="col-md-1">
                    {%if order.payed %}
                        <i style='color: green' class="fa fa-thumbs-o-up" aria-hidden="true"></i>
                    {%else%}
                        <a href='{{path('confirmPayed',{'singleId':order.id})}}'<i style='color: red' class="fa fa-thumbs-o-down" aria-hidden="true"></i></a>
                    {% endif %}
                </div>
                <div class="col-md-2">{{order.name}}</div>
                <div class="col-md-6">{{order.product.displayName}}</div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

src/AppBundle/Resources/views/Orders/history.html.twig
{% extends 'base.html.twig' %}
{% block content %}
    <h3>Following Total Orders are available</h3>
    <div class="container container-fluid">

        {% for totalOrder in allOrders %}
            <div class="row">
                <div class="col-md-1">
                    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                        <a href="{{path('editTotal',{'totalId':totalOrder.id})}}">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                        </a>
                    {% endif%}
                    <a href="{{path('displayTotalOrder',{'totalId':totalOrder.id})}}">
                        <i class="fa fa-list-ol" aria-hidden="true"></i>

                    </a>
                </div>
                <div class="col-md-1">
                    {{totalOrder.date|date('d.m.y')}}
                </div>
                <div class="col-md-1">
                    {%if totalOrder.active %}
                        Open
                    {% else %}
                        Closed
                    {% endif%}
                </div>
                <div class="col-md-3">
                    {{totalOrder.amount}} €
                </div>
                <div class="col-md-9">
                    {{totalOrder.text}}
                </div>
            </div>

        {% endfor %}

    </div>
{% endblock %}

src/AppBundle/Resources/views/Orders/single.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_3_layout.html.twig' %}
{% block content %}

    {{ form_start(form) }}
    {{ form_errors(form) }}
    <h3>Place your Order</h3>
    <div class="container-fluid">
        <div class="row">   
            <div class="col-md-3">
                {{ form_label(form.name) }}
                {{ form_errors(form.name) }}
                {{ form_widget(form.name) }}
            </div>
            <div class="col-md-9">
                {{ form_label(form.product) }}
                {{ form_errors(form.product) }}
                {{ form_widget(form.product) }}
            </div>
        </div>
        <div class="row">   
            <div class="col-md-12">
                {{ form_label(form.text) }}
                {{ form_errors(form.text) }}
                {{ form_widget(form.text) }}
                <ul>
                    <li>Garlic +0.5€</li>
                    <li>Any Change +1€ each</li>
                </ul>
            </div>

        </div>
        <br/>
        <div class="row">
            <div class="col-md-12">
                {{ form_widget(form.save) }} {{ form_widget(form.cancel) }}
            </div>
        </div>
    </div>

    {{ form_end(form) }}
{% endblock %}

src/AppBundle/Resources/views/Orders/total.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_3_layout.html.twig' %}
{% block content %}

    {{ form_start(form) }}
    {{ form_errors(form) }}
    <h3>Total Order</h3>
    <div class="container-fluid">
        <div class="row">

            <div class="col-md-3">
                {{ form_label(form.text) }}
                {{ form_errors(form.text) }}
                {{ form_widget(form.text) }}
            </div>
            <div class="col-md-3">
                {{ form_label(form.code) }}
                {{ form_errors(form.code) }}
                {{ form_widget(form.code) }}
            </div>

        </div>
        <div class="row">

            <div class="col-md-3">
                {{ form_label(form.active) }}
                {{ form_errors(form.active) }}
                {{ form_widget(form.active) }}
            </div>
        </div><br/>
        <div class="row"><div class="col-md-12">
                {{ form_widget(form.save) }} {{ form_widget(form.cancel) }}
            </div>
        </div>
    </div>

    {{ form_end(form) }}
{% endblock %}

src/AppBundle/Resources/views/Orders/totalByProduct.html.twig
{% extends 'base.html.twig' %}
{% block content %}
    <h3>Orders for {{totalOrder.date|date('d.m.y')}}</h3>
    <div class="container container-fluid">
        <div class="row">
            <div class="row">
                <div class="col-md-6">
                    <h3>Total Amount:&nbsp;<b>{{totalOrder.amount}}€</b></h3>
                </div><div class="col-md-6">
                    <h3>Total Orders Count:&nbsp;<b>{{totalOrder.orders|length}}</b></h3>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <a href="{{path('editTotal',{'totalId':totalOrder.id})}}">
                    <h3><i class="fa fa-pencil-square-o" aria-hidden="true"></i>&nbsp;Edit Order</h3>
                </a>
            </div>
            <div class="col-md-6">
                <a href="{{path('displayTotalOrder',{'totalId':totalOrder.id})}}">
                    <h3><i class="fa fa-eye" aria-hidden="true"></i>&nbsp;Display By Name</h3>
                </a>
            </div>

        </div>

        {% for product in products %}
            <div class="row" style="background-color: {{ cycle(["#e6f2ff", "white"], loop.index) }}">
                <div class="col-md-1">
                    {{product.count}}
                </div>
                <div class="col-md-5">
                    {{product.product.name}} - {{product.product.group.name}}
                </div>
                <div class="col-md-6">
                    <ul>
                        {% for comment in product.comments %}
                            <li>{{comment}}</li>
                            {% endfor %}
                    </ul>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}